image: ubuntu:22.04

variables:
  DATABASE_URL: "postgresql://user:password@test-db/test_db"

before_script:
  - echo "before_script"

scripts:
  - echo "scripts"
  - sh main.sh
  - echo $DATABASE_URL

after_script:
  - echo "Cleaning up..."

artifacts:
  paths:
    - htmlcov/
