image: python:3.10-slim

variables:
  DATABASE_URL: "postgresql://user:password@test-db/test_db"

before_script:
  - pip install -r requirements.txt

scripts:
  - flake8 .
  - pytest --cov=my_app --cov-report=html
  - echo "Build finished successfully!"

after_script:
  - echo "Cleaning up..."

artifacts:
  paths:
    - htmlcov/
